tidev/vscode-titanium

src/quickpicks/common.ts

fix: add spacing between sim device and version

---

src/explorer/nodes/osVerNode.ts
src/explorer/nodes/targetNode.ts
src/utils.ts

Added wp to windows targets and added windows device support

fix(Windows Targets): Add wp to windows targets

---

src/commands/createApp.ts
src/commands/createModule.ts

Oversight on my part from #50
Fixes #60
1. Create a project through the command palette
Project should create just fine and be able to be opened

fix(create): pass in log level to create argument builder

---

src/commands/alloyGenerate.ts

As the item we were checking for existence was a folder that would fail to open in the TextDocument calls, so we return an array of files to open and loop through that opening each one
Also fixes up the handling of a user cancellation on the dialogs
Fixes #55
1. Create a widget through the command palette
2. Click "open" in the information message
Widget files should open
A quick second set of eyes over the model/controller/styles creation wont go amiss

fix(alloy/generate): handle opening widget files

---

src/commands/alloyGenerate.ts

Also refactors to use the common quickpick in this file as opposed to custom
Fixes issue #58

fix(create/model): add adapter type to model creation

---

src/commands/buildApp.ts

Fixed the issue where the last target is undefined
Fixes #57

fix(build): last target undefined

---

src/commands/buildApp.ts
src/commands/buildModule.ts
src/commands/createApp.ts
src/commands/createModule.ts
src/commands/packageApp.ts
src/types/cli.ts
src/types/common.ts
src/utils.ts

Also improve typings of CLI arguments to try and help avoid issues like this in future
Fixes #67

fix(build/module): pass project dir and build only on module build

---

src/commands/packageApp.ts
src/types/cli.ts
src/utils.ts

fix(package): pass project directory into package arguments

---

src/commands/createApp.ts
src/commands/createModule.ts
src/constants.ts
src/quickpicks/common.ts
src/quickpicks/creation.ts

Improved the app creation flow so the user can better understand folder selection and auto selected platforms
Fixes #66

refactor(AppCreation): improves the folder selection in app creation

---

src/providers/definition/controllerDefinitionProvider.ts
src/providers/definition/definitionProviderHelper.ts

Fixed the link between widgets when formatted like `com.appc.testwidget`
Fixes #62

fix(providers): fix the link for the widget identifier

---

src/extension.ts

Changed generate completions to be non blocking and fixed the messages to show the status of the
generation
Fixes #22

refactor(completions): changed generate completions to non blocking

---

grammars/tss.JSON-tmLanguage.json
package.json
src/extension.ts
src/providers/completion/alloyAutoCompleteRules.ts
src/providers/completion/styleCompletionItemProvider.ts
tslint.json
tssConf.json

Added auto closing for quotes and brackets in the tss file and modified the style auto complete to
behave the same for know tags

fix(providers): added auto close for quotes and brackets for tss

---

.vscodeignore
configuration.md
images/dark/link-external.svg
images/light/link-external.svg
package-lock.json
package.json
src/commands/common.ts
src/constants.ts
src/explorer/nodes.ts
src/explorer/nodes/blankNode.ts
src/explorer/nodes/updateNode.ts
src/explorer/updatesExplorer.ts
src/extension.ts
src/providers/completion/completionItemProviderHelper.ts
src/quickpicks/common.ts
src/terminal.ts
src/types/config.ts
src/utils.ts
tsconfig.json

Closes #48
This PR introduces update checking to the extension. When the extension is started we will run a check in the background for any updates, by default once a day if there's updates we'll pop up a notification informing of any updates.
Updates will always be shown in the updates explorer alongside the device explorer, and can be installed from there.
* When the extension starts up, before the the device explorer is populated the extension validates that the environment has the required components (limited for now to Appc CLI (core/npm), and Titanium SDK). If any of these are missing the extension will prompt to install these.
* Additionally, if the SDK version used by the app is not installed. The extension will prompt to install that.
Demo of environment validation - …

feat(updates): add update functionality

---

package-lock.json
package.json

chore(deps): update fs-extra to version 8.0.1

---

src/extension.ts

Check if there are multiple SDKs in the tiapp and then throws an error.
Fixes #79

fix(autocomplete): check if there are multiple sdks in tiapp

---

src/quickpicks/common.ts
src/utils.ts

Prompt for Keystore Key Password, added optional Keystore Key Password input box on the android
packaging flow.

feat(package/android): prompt for keystore key password

---

src/providers/definition/common.ts
src/providers/definition/definitionProviderHelper.ts

fix(definition): fixed go to definition for event handlers

---

src/explorer/updatesExplorer.ts
src/extension.ts

fix(validation): correct verbiage on fail message
Fixes #88
fix(updates): handle error properly in update check 
Report that an error had occured to the user when checking for updates, only check for updates in the updat explorer to reduce duplication
Fixes #100
Please rebase and merge so both commits stay

Various fixes

---

src/commands/createApp.ts
src/commands/createModule.ts
src/quickpicks/common.ts

Also use Uri.file instead of parse to ensure we parse the path correctly
Fixes #108

fix(creation): use fsPath when dealing with selected directory

---

grammars/tss.JSON-tmLanguage.json

fix(tmlanguage): fixed highlighting when using comments in tss

---

src/terminal.ts

fix(creation): show output when error on app/module creation

---

src/providers/completion/styleCompletionItemProvider.ts

Fixed issue where Ti.UI.SIZE/FILL are not shown
fixes #122

fix: fixed issue where ti.ui.size/fill were missing

---

package-lock.json
package.json

Fixes an issue where sdks and modules were being extracted and executables were losing their permissions

chore(deps): update titanium-editor-commons to 0.4.0

---

package.json
src/commands.ts
src/commands/clean.ts
src/commands/common.ts
src/extension.ts
src/quickpicks/common.ts
src/types/cli.ts
src/utils.ts

Added clean command to vscode command palette
fixes #141

feat: add clean to command palette

---

src/appc.ts
src/commands/buildApp.ts
src/commands/packageApp.ts
src/quickpicks/common.ts
src/test/suite/appc.test.ts
src/test/suite/utils.test.ts
src/types/common.ts
src/utils.ts

Add support for using the Apple certificates, and also fix a bug where we would prompt for the cert info even if we had it
Please rebase and merge this PR

Support apple certificates

---

src/debugger/titaniumPathTransformer.ts
src/debugger/titaniumSourceMapTransformer.ts

Add support for platform-specific breakpoints and subfolders within platform folder
fixes #129

fix(debugger): add support for platform specific breakpoints

---

package-lock.json
package.json
src/extension.ts
src/providers/completion/controllerCompletionItemProvider.ts
src/providers/completion/styleCompletionItemProvider.ts
src/providers/completion/viewCompletionItemProvider.ts
src/test/suite/controllerAutoCompleteProvider.test.ts
src/test/suite/fixtures/data/completions.json
src/test/suite/fixtures/sample.js
src/test/suite/styleAutoCompleteProvider.test.ts
src/test/suite/viewAutoCompleteProvider.test.ts
tslint.json

Added alloy namespace to completions and updated to get version 2 of the generated completions.
Fixes #133

feat(completions): added completions for Alloy namespace in controllers

---

src/providers/completion/alloyAutoCompleteRules.ts
src/providers/completion/controllerCompletionItemProvider.ts

Improved file path completions for images, require and added the ability to ask for the range for alloy auto complete rules
fixes #176

fix(providers): improve file path completions

---

src/providers/definition/controllerDefinitionProvider.ts

feat(definition/controller): fix lookup when path contains app

---

src/commands/alloyGenerate.ts

https://jira.appcelerator.org/browse/EDITOR-42

fix(generate): fixed typo in alloy generate components

---

src/tasks/helpers/android.ts

feat(tasks): resolve keystore relative to task folder

---

.gitignore
.vscode/launch.json
Jenkinsfile
package-lock.json
package.json
src/test/index.ts
src/test/runTest.ts

* Setup code coverage for the extension via nyc
* Hook into Jenkins
* Restructure the `launch.json` file and the output view to keep the related components together

Setup code coverage

---

CONTRIBUTING.md
package.json
src/commands/common.ts
src/debugger/titaniumDebugConfigurationProvider.ts
src/explorer/nodes/baseNode.ts
src/explorer/nodes/deviceNode.ts
src/explorer/nodes/osVerNode.ts
src/explorer/nodes/targetNode.ts
src/extension.ts
src/tasks/buildTaskProvider.ts
src/tasks/tasksHelper.ts
src/types/cli.ts
src/utils.ts

Rather than contribute a load of tasks I went for the easier option of sharing state between the debug command the tasks
Closes EDITOR-13

feat(debugging): allow starting a debug session from build explorer

---

doc/tasks.md
package.json
src/commands/buildApp.ts
src/quickpicks/common.ts
src/tasks/helpers/ios.ts

https://jira.appcelerator.org/browse/EDITOR-39

feat: allowed simulatorVersion to be set on iOS tasks

---

src/tasks/helpers/base.ts

fix(packaging): allow selecting folders during packaging

---

src/tasks/helpers/base.ts

feat: added ability to output iOS App Store builds to Xcode

---

src/quickpicks/build/android.ts
src/tasks/helpers/android.ts

This was inadvertently removed in the move to task based building
Fixes #438

fix(package/android): respect keystore settings

---

Jenkinsfile

Appears to be an issue with npm 7 somwehere in the dep tree

ci: pin to npm 6

---

src/quickpicks/common.ts
src/quickpicks/creation.ts

fix(quickpick): return array from quickpick if canPickMany is true

---

package-lock.json
package.json
src/extension.ts
src/providers/completion/baseCompletionItemProvider.ts
src/providers/completion/controllerCompletionItemProvider.ts
src/providers/completion/styleCompletionItemProvider.ts
src/providers/completion/tiappCompletionItemProvider.ts
src/providers/completion/viewCompletionItemProvider.ts
src/providers/index.ts

* Make all completion providers extend a base class that handles the completion loading
* Store the completions format in a single variable that is used for loading and generation of the completions
This fix will need to also land on a (to be created) 0_10_X branch to avoid us releasing the work we have in progress

Fix generation of Titanium completions

---

Jenkinsfile
package-lock.json
package.json
src/extension.ts
src/providers/completion/baseCompletionItemProvider.ts
src/providers/completion/controllerCompletionItemProvider.ts
src/providers/completion/styleCompletionItemProvider.ts
src/providers/completion/tiappCompletionItemProvider.ts
src/providers/completion/viewCompletionItemProvider.ts

#595 for the 0_10_X branch.
The first two commits are cherry-picks but the last commit is different as the extension.ts refactor came after 0.10.0

refactor(completions): move completions loading to a base class

---

.github/workflows/ci.yml
.github/workflows/integration-tests.yml

Run against only latest VS Code in PR's, run a daily job to run against oldest supported, latest, and insiders VS Code if there have been changes in the repo

Change up integration tests

---

src/providers/definition/baseDefinitionProvider.ts
src/providers/definition/common.ts
src/providers/definition/viewDefinitionProvider.ts
src/test/common/fixtures/alloy-project/app/views/sample.xml
src/test/unit/suite/providers/completion/view.test.ts
src/test/unit/suite/providers/definition/style.test.ts
src/test/unit/suite/providers/definition/view.test.ts

The other text changes were related to fixing the formatting in the view file

fix(providers/view): fix issues when providing definitions that included punctuation

---

src/debugger/titaniumPathTransformer.ts
src/debugger/titaniumSourceMapTransformer.ts

Requires appcelerator/alloy/pull/1173 as it will generate the sourcemap file
Fixes #140

fix(debugger): support breakpoints in widget lib files

---

package-lock.json
package.json
src/updates/index.ts

fix(updates): update editor commons to fix passing of error metadata

---

Jenkinsfile
package-lock.json
package.json
src/providers/completion/baseCompletionItemProvider.ts
src/providers/completion/controllerCompletionItemProvider.ts
src/providers/completion/styleCompletionItemProvider.ts
src/providers/completion/viewCompletionItemProvider.ts
src/test/common/fixtures/alloy-project/app/styles/sample.tss
src/test/unit/suite/providers/completion/style.test.ts
src/test/unit/utils.ts

Refactors out the any usage from the completions provider

refactor(completions): remove any type on completions data

---

src/providers/definition/common.ts
src/test/common/fixtures/alloy-project/app/controllers/sample.js
src/test/common/fixtures/alloy-project/app/views/sample.xml
src/test/unit/suite/providers/definition/view.test.ts

fix(providers/definition): handle event handlers that are variable declarations

---

src/providers/definition/viewDefinitionProvider.ts
src/test/common/fixtures/alloy-project/app/styles/app.tss
src/test/common/fixtures/alloy-project/app/styles/sample.tss
src/test/common/fixtures/alloy-project/app/views/sample.xml
src/test/unit/suite/providers/completion/view.test.ts
src/test/unit/suite/providers/definition/view.test.ts

fix(providers/definition): correctly parse out individual classes from view tags

---

package.json
src/commands/common.ts
src/explorer/index.ts

feat(explorer/recent): allow removing all recent builds

---

.github/workflows/ci.yml
package.json
src/commands/common.ts
src/commands/createApp.ts
src/commands/createKeystore.ts
src/commands/createModule.ts
src/commands/index.ts
src/container.ts
src/environment-info.ts
src/explorer/nodes/errorNode.ts
src/explorer/nodes/updatesNode.ts

This should at least help provide some avenue for people to investigate what's wrong,
once landed we can maybe look at updating titanium-editor-commons to include better output

fix(updates): output error to output channel and allow viewing it

---

.github/workflows/ci.yml
.github/workflows/integration-tests.yml
.github/workflows/release.yml

16 seems a little crashy running tsc recently

ci: update node version

---

src/commands/createApp.ts

Adding an option to enable/disable Alloy projects when creating a new project:

feat: option for Alloy/Classic project creation

---

.github/workflows/ci.yml
.github/workflows/integration-tests.yml
.github/workflows/release.yml
package-lock.json
package.json

* update workflows
* update node version
* update titanium-editor-commons

chore: update packages

---

.github/workflows/integration-tests.yml
.vscodeignore
package-lock.json
package.json
src/commands/createApp.ts
src/test/integration/suite/keystore/create.test.ts
src/test/integration/suite/smoke/app.smoke.ts
src/test/integration/suite/smoke/module.smoke.ts
src/test/integration/types.ts
src/test/integration/util/common.ts
src/test/integration/util/project.ts
tsconfig.json

Updates vscode-extension-tester and gets the tests working again (at least on my machine)

test: get ui tests working 
