tidev/vscode-titanium

- package.json
- src/appc.ts
- src/commands/buildApp.ts
- src/commands/buildModule.ts
- src/commands/packageApp.ts
- src/configuration.ts
- src/constants.ts
- src/container.ts
- src/extension.ts
- src/providers/completion/alloyAutoCompleteRules.ts
- src/providers/definition/common.ts
- src/providers/definition/definitionProviderHelper.ts
- src/types/common.ts
- src/types/config.ts
- src/utils.ts
This PR refactors the config management of the extension to only get/update settings through the ExtensionContainer class.
It includes the fix for #46
> refactor: move config management to ExtensionContainer

- src/commands/packageApp.ts
- src/types/common.ts
Object.assign is not a deep copy like I thought, just null the passwords out manually on buildInfo before storing
Fixes #47
1. Package for Android via the command palette
2. Package for last run via the command palette
2. Package for Android via the activity pane
> fix(package): correct last build state for android

- package.json
- src/commands/packageApp.ts
- src/quickpicks/common.ts
- src/types/config.ts
Allows the user to have the keystore path and alias saved in the settings.json.
Fixes #51 
1. Add settings `titanium.android.keystorePath` and or `titanium.android.keystoreAlias` to the .vscode settings file
2. Package an to an android application using the saved keystore path
> feat(config): add support for setting default keystore path

- grammars/tss.JSON-tmLanguage.json
Fixed the syntax highlighting for Alloy.CFG to highlight the same as Alloy.Globals
Fixes #103
> fix(textmate): fixed syntax highlight for alloy.cfg

- src/utils.ts
We need to ensure the drive letter is uppercased to prevent an infinite loop in the SDK build process
Fixes #142
> fix: ensure correct drive letter is used when normalizing path

- src/providers/completion/styleCompletionItemProvider.ts
- src/providers/completion/viewCompletionItemProvider.ts
Fixed the completions in tss files where the completions would not take into account the word
fragment already there.
fixes #150
> fix: fixed value completions in tss and views with word fragment

- src/debugger/titaniumDebugConfigurationProvider.ts
Dependent on the SDK version used we need to provide the full name or the short name of the
certificate. This was done on build/package commands but not on the debug code
Fixes #166
> fix(debug/ios): obtain correct certificate name

- src/debugger/titaniumDebugConfigurationProvider.ts
To test:
1. Debug for Android - it should actually work
> fix(debugging/android): correctly assign default port

- src/commands/buildApp.ts
To repro:
1. Build to a simulator following the usual prompting
2. Perform another build and select the `Last build` option (should be the last simulator you chose), it should work
> fix(commands/run): only do certificate name check when targeting device

- doc/debugging.md
- package.json
- src/common/extensionProtocol.ts
- src/debugger/titaniumDebugAdapter.ts
- src/debugger/titaniumDebugConfigurationProvider.ts
- src/debugger/titaniumDebugHelper.ts
- src/debugger/titaniumSourceMapTransformer.ts
- src/extension.ts
- src/tasks/buildTaskProvider.ts
- src/tasks/helpers/android.ts
- src/tasks/helpers/base.ts
- src/tasks/helpers/ios.ts
- src/tasks/taskPseudoTerminal.ts
- src/tasks/tasksHelper.ts
- src/types/cli.ts
- src/utils.ts
This PR changes the debugger to allow specifying a preLaunchTask in the configuration to build the application. If no preLaunchTask is specified we will create and add one to the tasks file.
Introduces a breaking change where we no longer support setting target and deviceId on the launch config, instead use a preLaunchTask to specify these.
Also cleans up some unused code, eslint warnings, and removes the debug activation into a `registerDebugProvider` function invoked in activates (we should continue to do this as we touch things imo)
JIRA: https://jira.appcelerator.org/browse/EDITOR-36
> refactor(debugger)!: use tasks for building application

- configuration.md
- package.json
- src/appc.ts
- src/constants.ts
- src/explorer/nodes/osVerNode.ts
- src/explorer/nodes/platformNode.ts
- src/explorer/nodes/targetNode.ts
- src/project.ts
- src/quickpicks/common.ts
- src/test/suite/fixtures/data/ti_info.ts
- src/types/cli.ts
- src/types/common.ts
- src/types/config.ts
- src/types/environment-info.ts
- src/utils.ts
* We didn't add support to tasks for building Windows applications, so keeping the activity pane information around didn't make much sense as it did nothing - [EDITOR-35](https://jira.appcelerator.org/browse/EDITOR-35)
* Bump the min node version to 12.4.0 in accordance with our min VSCode version
> Remove windows platform from activity pane, bump minimum node version

- doc/debugging.md
- src/debugger/titaniumDebugConfigurationProvider.ts
- src/debugger/titaniumDebugHelper.ts
- src/tasks/buildTaskProvider.ts
- src/tasks/helpers/android.ts
- src/tasks/helpers/base.ts
- src/tasks/taskPseudoTerminal.ts
- src/tasks/tasksHelper.ts
* Add `provideTasks` to the `BuildTaskProvider` and use those tasks as the default `preLaunchTask` so we don't need to add tasks into a users project just t o debug.
* [EDITOR-46](https://jira.appcelerator.org/browse/EDITOR-46) - Always make sure we set `--debug-host` when debugging on Android
* [EDITOR-43](https://jira.appcelerator.org/browse/EDITOR-43) - Make sure we respect the global liveview setting when using a task
* [EDITOR-47](https://jira.appcelerator.org/browse/EDITOR-47) - Allow killing a task using `CTRL+C`
> Pre launch task refactor

- src/commands/buildApp.ts
- src/commands/common.ts
- src/commands/createApp.ts
- src/commands/createModule.ts
- src/commands/packageApp.ts
- src/common/extensionProtocol.ts
- src/common/utils.ts
- src/debugger/titaniumDebugConfigurationProvider.ts
- src/debugger/titaniumPathTransformer.ts
- src/debugger/titaniumTargetDiscovery.ts
- src/explorer/nodes/platformNode.ts
- src/extension.ts
- src/project.ts
- src/providers/completion/alloyAutoCompleteRules.ts
- src/providers/completion/controllerCompletionItemProvider.ts
- src/providers/completion/styleCompletionItemProvider.ts
- src/providers/completion/tiappCompletionItemProvider.ts
- src/providers/completion/viewCompletionItemProvider.ts
- src/providers/definition/common.ts
- src/providers/definition/definitionProviderHelper.ts
- src/providers/definition/viewHoverProvider.ts
- src/quickpicks/common.ts
- src/quickpicks/creation.ts
- src/tasks/helpers/ios.ts
- src/tasks/taskPseudoTerminal.ts
- src/terminal.ts
- src/test/suite/controllerAutoCompleteProvider.test.ts
- src/test/suite/styleAutoCompleteProvider.test.ts
- src/test/suite/viewAutoCompleteProvider.test.ts
- src/utils.ts
This brings us down to around 61 warnings from around 119. That's still a good chunk of warnings, but I focused on things I can fix within a couple minutes and avoided anything that requires significant refactors like `workspace.rootPath` for example.
I tried to group related fixes so that's why there's a bunch of commits. We can just squash this PR on merge as they're not all necessary.
> refactor: reduce number of lint warnings

- doc/debugging.md
libimobiledevice has released a new version which means that we can remove the manual install steps for that and libusbmuxd in the debugging guide
> docs(debugging): remove manual install of iwdb dependencies

- .vscode/launch.json
- src/commands/alloyGenerate.ts
- src/test/integration/suite/alloy/generate.test.ts
- src/test/integration/util/alloy-generate.ts
- src/test/integration/util/create.ts
- src/types/telemetry.ts
* Move to a pattern where we check that the right prompt is shown before attempting to input text, that should allow us to track down issues easier
* Fix the command names for creating apps/modules, was changed in #366 (to be pushed after I've tested how these failures look in Jenkins)
> Fix integration tests

- package.json
- src/quickpicks/common.ts
- src/test/integration/util/common.ts
- src/test/integration/util/create.ts
- src/types/config.ts
Closes [EDITOR-53](https://jira.appcelerator.org/browse/EDITOR-53)
Reworks the quick fix for inputting a folder that was put in place to get the integration tests going.
There's no clean way to have a quick-pick function as a selection and input box, so rather than allow inputting the path directly I decided to rework the feature into allowing a default creation path to be set. We configure that before running the tests and then set the path as needed on each test run
> feat(create): allow setting a default path for project

- src/explorer/tiExplorer.ts
- src/extension.ts
- src/quickpicks/build/android.ts
- src/quickpicks/build/common.ts
- src/quickpicks/build/ios.ts
- src/quickpicks/common.ts
- src/tasks/buildTaskProvider.ts
- src/tasks/helpers/android.ts
- src/tasks/helpers/base.ts
- src/tasks/helpers/ios.ts
- src/tasks/packageTaskProvider.ts
* Splits out the build quickpicks into separate files in the hopes of reducing the chonky `quickpicks/common.ts` file down
* Adds a `Refresh Devices` option to the device list that will trigger and wait for the refresh explorer command to run before re-prompting
* Moves the common tasks code to use `selectDevices` instead of each platform handling their own device selection
> Add refresh devices option on device selection, refactor build quickpicks into separate files

- Jenkinsfile
- dangerfile.js
- src/test/integration/suite/create/app.test.ts
- src/test/integration/suite/create/module.test.ts
- src/test/integration/util/common.ts
- src/test/integration/util/create.ts
We didn't make use of try/finally around the stages so if one stage failed the build would exist and not report anything to the PR. This wraps the stages in a try/finally and runs danger in the finally so that we always get output.
Also includes the integration tests junit report in the output
> Fix Jenkinsfile usage

- package.json
- src/common/utils.ts
- src/debugger/titaniumDebugAdapter.ts
- src/extension.ts
Rather than hiding the run button if a build is currently active, it will now always show and when
clicked it will cancel the running build and begin the flow for a new build to occur
Closes #436
> feat(explorer): always show run button, stop running build if clicked

- src/appc.ts
- src/constants.ts
- src/explorer/nodes/targetNode.ts
- src/explorer/tiExplorer.ts
[EDITOR-57](https://jira.appcelerator.org/browse/EDITOR-57)
* Updates the `appc.ts` environment function to use optional chaining to avoid an error being thrown when accessing `this.info` before we have completed reading the infor
* Updates the build explorer to explicitly handle the following:
** Show a `Refreshing environment` message when we're loading the data (first startup, or from clicking Refresh Devices)
** Show a `No $type detected` message if none of that type is detected.
* Cleans up some unused code in appc.ts
> Improve handling of no environment information in build explorer

- src/commands/createModule.ts
- src/quickpicks/creation.ts
- src/test/integration/suite/create/module.test.ts
- src/test/integration/types.ts
- src/test/integration/util/create.ts
- src/types/cli.ts
- src/utils.ts
If the selected SDK is >= 9.1.0 and the CLI is >= 8.1.1 then prompt for the code base to be used for the module
Closes [EDITOR-65](https://jira.appcelerator.org/browse/EDITOR-65)
> feat(creation/module): support selecting android and ios codebase

- doc/tasks.md
- package-lock.json
- package.json
- src/explorer/tiExplorer.ts
- src/explorer/updatesExplorer.ts
- src/tasks/buildTaskProvider.ts
- src/tasks/commandTaskProvider.ts
- src/tasks/taskPseudoTerminal.ts
This allows the usage of [VS Codes variables](https://code.visualstudio.com/docs/editor/variables-reference) in tasks. This is mostly useful for setting paths in properties such as `outputDirectory` in tasks that maybe used across machines e.g. `"outputDirectory": "${workspaceFolder}/dist",`
Closes [EDITOR-48](https://jira.appcelerator.org/browse/EDITOR-48)
Note: this will raise the minimum VS Code to 1.49.0 (August 2020)
> Support variable substitution in tasks

- src/test/integration/suite/alloy/generate.test.ts
- src/test/integration/suite/create/app.test.ts
- src/test/integration/suite/create/module.test.ts
- src/test/integration/util/common.ts
- src/test/integration/util/create.ts
* Contains a hack to sleep while the `Appc.getInfo` call in the create module flow finishes
* Adds a wait in the `beforeEach` of each test for the environment detection to finish
* Only removes the tempDirectory if we created one as sometimes the test setup can barf before we get to creating it
> Integration test improvements

- scripts/templates/tasks.md.ejs
- src/tasks/taskPseudoTerminal.ts
close is be called twice, once when terminate is called from StopBuild and then a second time when
from the close event listener on our subprocess. By checking the cancellation token status we avoid
rerunning the close code twice which can put us into an invalid state if we're performing a rebuild
Also removes the limitations note from the ejs template for tasks as I forgot to remove it from there before
To reproduce, click the play button on a device in the device treeview multiple times. It should start new builds with no problems
> fix(tasks/build): check cancellation status before closing terminal

- src/appc.ts
- src/commands/createModule.ts
- src/explorer/tiExplorer.ts
- src/extension.ts
[EDITOR-72](https://jira.appcelerator.org/browse/EDITOR-72)
If the `appc ti info` command fails this will send the output of that command to a output channel and prompt the user to check it out, this hopefully might make it easier to debug issues like #484
> feat: surface error from environment detection if one occurs

- src/commands/index.ts
- src/extension.ts
- src/providers/definition/definitionProviderHelper.ts
- src/providers/index.ts
- src/quickpicks/common.ts
This PR fixes a couple issues I noticed with the updates flow, namely:
* We would ask the user to select updates, then install them all irregardless of what they asked
* The progress notification would stick around until the information message was dismissed. Now it disappears as soon as the flow is finished
> Fix installing all updates instead of selected, fix issue with updates progress notification sticking around

- src/commands/index.ts
- src/constants.ts
- src/container.ts
- src/explorer/updateExplorer.ts
- src/extension.ts
- src/quickpicks/common.ts
- src/updates/index.ts
This PR is a continuation of #531 and finishes off separating out the startup code into the 3 main states we care about:
* Required tooling is missing
* Tooling installed but no Titanium project open
* Tooling installed and Titanium project open
From here we can then start creating the welcome views for the activity bar that will show.
It also refactors the update commands to reduce the duplicate code we had
> Refactor update commands to reduce dupe code, refactor startup code to separate out different states

- package.json
Adds welcome views that will show when the user has no tooling installed
Or when no Titanium project is open
> Add welcome views for no tooling and no titanium project states

- package-lock.json
- package.json
- src/common/extensionProtocol.ts
- src/debugger/titaniumDebugAdapter.ts
- src/debugger/titaniumDebugger.ts
- src/debugger/titaniumPathTransformer.ts
- src/debugger/titaniumSourceMapTransformer.ts
- src/debugger/titaniumTargetDiscovery.ts
* dda26e8f756ca8ddb8e948d820f4d9e3ce0ab1f8 replaces the fork of vscode-chrome-debug-core as we can now use the mainline package with no issues (there was a typing issue that required the fork)
* 3ac8e9913ed7e0d0b72c9f124946617a09654433 updates the translation layer between iOS and VS Code to handle some changes in the debug protocol that look to have appeared around iOS 13.4
> Fix issues with variables view not displaying variables on newer iOS versions

- README.md
- package-lock.json
- package.json
- scripts/templates/README.md.ejs
- src/appc.ts
- src/commands/alloyGenerate.ts
- src/commands/clean.ts
- src/commands/common.ts
- src/commands/createApp.ts
- src/commands/createModule.ts
- src/common/utils.ts
- src/configuration.ts
- src/container.ts
- src/debugger/titaniumDebugHelper.ts
- src/extension.ts
- src/project.ts
- src/providers/definition/common.ts
- src/providers/definition/viewHoverProvider.ts
- src/quickpicks/creation.ts
- src/tasks/commandTaskProvider.ts
- src/tasks/helpers/android.ts
- src/tasks/helpers/base.ts
- src/tasks/helpers/ios.ts
- src/tasks/taskPseudoTerminal.ts
- src/terminal.ts
- src/types/config.ts
- src/utils.ts
This PR introduces support for using the Ti and Alloy (OSS) tooling directly instead of the Appc tooling. It is enabled using the `titanium.general.useTi` setting which can be set in the global settings or on a per-workspace/project level with a `.vscode/settings.json` file.
Again the PR is split up into the individual components to hopefully make it easier to review, I'll squash all relevant commits before merge to keep the changelog tidy.
The following are standalone commits that won't be squashed:
* 36bb58bdda34d9aad769286ef0304a52f39e6a08 - Removes most of the Terminal class as I realised it's mostly unused after we moved to tasks, we can probably remove this completely once we remove the Appc tooling.
* 7d4499a47325180d7732931dd6b3938d23290a28 - Linting stuff
* …
> Support using OSS Tooling

- .editorconfig
- .github/workflows/ci.yml
- Jenkinsfile
- package.json
- runUITests.sh
- src/test/integration/.mocharc.ts
- src/test/integration/fixtures/settings.json
- src/test/integration/runTests.ts
- src/test/integration/suite/alloy/generate.test.ts
- src/test/integration/suite/create/app.test.ts
- src/test/integration/suite/create/module.test.ts
- src/test/integration/types.ts
- src/test/integration/util/common.ts
- src/test/integration/util/create.ts
- src/updates/index.ts
Moves the existing integration tests over to OSS tooling and gets them running in actions against the lowest supported VS Code, latest VS Code, and nightly VS Code
> Move integration tests to use OSS tooling, run in Actions

- package.json
- src/commands/index.ts
- src/explorer/nodes/baseNode.ts
- src/explorer/nodes/distributeNode.ts
- src/explorer/nodes/platformNode.ts
- src/explorer/nodes/targetNode.ts
- src/types/cli.ts
This PR attempts to improve the discoverability of packing by doing the following from #642
* Add a top level Package button alongside the Run button in the title bar of the Build Explorer
* Add a new Package sub-item to each platform in the Build Explorer that will list the possible distribution target
The second on is _slightly_ different in that each packaging target is listed individually rather than under a `Package` option. This was chosen because: 
* Although there are 2 options for iOS, Android only has one so it felt awkward
* The semantics fit better, emulator/simulator are targets (--target on the CLI), so (personally) it made sense to list the other targets alongside them
This is what the changes look like
> Improve packaging discoverability

- src/commands/buildApp.ts
- src/commands/buildModule.ts
- src/commands/packageApp.ts
- src/commands/packageModule.ts
- src/common/extensionProtocol.ts
- src/constants.ts
- src/container.ts
- src/explorer/nodes.ts
- src/explorer/nodes/recentNode.ts
- src/explorer/tiExplorer.ts
- src/tasks/buildTaskProvider.ts
- src/tasks/commandTaskProvider.ts
- src/tasks/helpers/base.ts
- src/tasks/helpers/index.ts
- src/tasks/packageTaskProvider.ts
- src/tasks/tasksHelper.ts
- src/types/cli.ts
- src/types/common.ts
- src/utils.ts
This PR implements the "Improving build recall" section of #643 by implementing a new node alongside the Android and iOS platforms that will list the 5 most recent builds like below
> Improve build recall

- src/commands/packageApp.ts
- src/tasks/buildTaskProvider.ts
- src/tasks/commandBuilder.ts
- src/tasks/commandTaskProvider.ts
- src/tasks/helpers/android.ts
- src/tasks/helpers/base.ts
- src/tasks/helpers/ios.ts
- src/tasks/packageTaskProvider.ts
- src/tasks/taskPseudoTerminal.ts
This has two benefits. Firstly, it allows us to avoid logging sensitive arguments like the keystore
password to the console, and secondly it allows it to support special characters in the keystore
password.
Closes EDITOR-66
Also fixes an issue when calling the package task not from a tree node
> feat(tasks): support passing arguments as environment variables

- doc/debugging.md
- package.json
- src/common/utils.ts
- src/container.ts
- src/debugger/titaniumDebugAdapter.ts
- src/debugger/titaniumDebugConfigurationProvider.ts
- src/project.ts
- src/tasks/buildTaskProvider.ts
- src/tasks/helpers/android.ts
This fixes a couple inconsistent issues around attaching to the Android debugger. It moves to using
a random port every time (unless specified by the user) due to an issue where a debug session could
fail to start due to the port already being in use, and adds a small delay to the attachment process
to allow time for the app to have got the debugger ready for attaching to
> fix(debug/android): improve reliability of Android debug attachment

- package-lock.json
- package.json
- src/commands/common.ts
- src/commands/generateTask.ts
- src/commands/index.ts
- src/explorer/helpExplorer.ts
- src/project.ts
- src/quickpicks.ts
- src/quickpicks/common.ts
- src/quickpicks/index.ts
- src/tasks/commandTaskProvider.ts
- src/tasks/helpers/base.ts
- src/tasks/packageTaskProvider.ts
- src/tasks/tasksHelper.ts
- src/types/common.ts
This adds support for generating a task via the right click context menu, the data is then used
to construct a task object and then add it into the tasks.json file, creating on if necessary.
Part of #643
Also fixes an issue with the reveal updates command where the UpdatesNode was only created when the explorer was shown. Now it's created when the explorer is created and can always be accessed
> feat: add a command to generate a task for a device or distribution target

- src/test/integration/suite/alloy/generate.test.ts
- src/test/integration/suite/create/app.test.ts
- src/test/integration/suite/create/module.test.ts
- src/test/integration/util/common.ts
This attempts to make the integration tests more resilient by avoiding multiple lookups of the
activity view and instead caching the result for the lifetime of the tests.
> test: make integration tests more resilient

- .github/workflows/ci.yml
They're flaky in ci and make noise. Nightly if changes fits better now there are better unit tests
> ci: dont run integration tests on pull request or push, only nightly

- package-lock.json
- package.json
- src/common/utils.ts
- src/constants.ts
- src/extension.ts
This add support for the upcoming workspace trust configuration, the support is rather blunt in
that the extension will not work unless the workspace has been trusted. This was chosen because
of the variety of ways this extensions works i.e. installing tooling, building project (which can
also have hooks that run code), so it made more sense to stick with the stricter and more secure
option
BREAKING CHANGE: Raises the minimum VS Code version to 1.56.0
> Support for vscode trusted workspaces and virtual workspaces

- package-lock.json
- package.json
- src/debugger/titaniumDebugConfigurationProvider.ts
- src/providers/completion/alloyAutoCompleteRules.ts
- src/providers/hover/viewHoverProvider.ts
- src/test/unit/index.ts
- src/updates/index.ts
- src/utils.ts
- tsconfig.json
Updates titanium-editor-commons to fix an oversight where the SDK wasn't selected after installing it. If any errors occur (for example `appc ti sdk` requires a login) then we'll prompt to run it in the terminal
Also fixes a deprecation warning in executeTask
> fix(updates): select Titanium SDK after installing it

- package-lock.json
- package.json
- src/appc.ts
- src/commands/common.ts
- src/commands/createKeystore.ts
- src/commands/index.ts
- src/quickpicks/build/android.ts
- src/tasks/commandBuilder.ts
- src/terminal.ts
- src/test/integration/fixtures/settings.json
- src/test/integration/suite/alloy/generate.test.ts
- src/test/integration/suite/keystore/create.test.ts
- src/test/integration/util/common.ts
- src/types/environment-info.ts
This adds support for creating a keystore and storing the keystore information. When packaging an
Android application there is now an extra "Create keystore" option. This will trigger a UI where
the information can be input, and optionally saved.
Also, when packaging for Android an extra "store information" dialog will be shown, this will store
the keystore information, using the path as they key, using the secure storage for the device.
Closes #89
> feat: add keystore creation and keystore information storage

- package-lock.json
- package.json
- src/commands/createKeystore.ts
- src/debugger/titaniumDebugConfigurationProvider.ts
- src/project.ts
- src/providers/completion/alloyAutoCompleteRules.ts
- src/providers/index.ts
- src/tasks/commandTaskProvider.ts
- src/test/integration/util/common.ts
- src/updates/index.ts
Updates TS to 4.4 and fixes the new errors, mostly the change in strict mode to alway treat `error` in catch clauses being `unknown` instead of `any`.
Will print a warning on `npm run lint` but it still functions
> build(deps): update to typescript 4.4

- src/providers/definition/controllerDefinitionProvider.ts
- src/test/common/fixtures/alloy-project/app/controllers/sample.js
- src/test/unit/suite/providers/definition/controller.test.ts
Along with ES5 `require` this should add support to CMD+Click:
```
import navigator from "core/navigator";
import "core/navigator";
```
to open the related file.
> feat(providers/definition): support ES6 import file lookups

- src/providers/completion/alloyAutoCompleteRules.ts
- src/providers/completion/viewCompletionItemProvider.ts
- src/providers/definition/baseDefinitionProvider.ts
- src/providers/definition/common.ts
- src/providers/index.ts
- src/test/common/fixtures/alloy-project/app/lib/folder/custom-view.js
- src/test/common/fixtures/alloy-project/app/views/sample.xml
- src/test/unit/suite/providers/completion/controller.test.ts
- src/test/unit/suite/providers/completion/view.test.ts
- src/test/unit/suite/providers/definition/view.test.ts
- tsconfig.json
This PR adds support for providing definition links for custom tags on the `module` attribute and also for completions for that attribute.
It also fixes the parsing of attributes when multiple are present in a single tag
> Add custom tag support, improve attribute detection

- package-lock.json
- package.json
This was seemingly causing an issues in some instances. We don't actually need everything else given that `*` means always so lets just remove them
Fixes #887
> fix: reduce activation events

- package-lock.json
- package.json
- src/commands/createKeystore.ts
It seems VS Code broke how the dependency loaded the webview assets
> fix: update dependency to fix keystore creation

- package.json
- src/explorer/helpExplorer.ts
old link leads to a 404 since we've changed the docs a while ago
> fix(explorer/help): update VS Code documentation link

- package.json
Otherwise it will fail due to the commit being longer than desired
> build: disable husky when releasing

- package.json
- src/test/unit/index.ts
This moves from the `*` activation event which means the extension is always activated to the following:
* `workspaceContains:**/tiapp.xml` - When the workspace has a tiapp.xml in a folder
* `onView:titanium` - When the `titanium` view is opened
We don't need to do any `onCommand` activation events as this is automatically done [as of VS Code 1.74](https://code.visualstudio.com/api/references/activation-events#onCommand) (which I think we should bump the minimum to on the next release)
> refactor: reduce number of activation events

- package.json
- src/extension.ts
This is a speculative fix for the issue described [in this thread](https://tidev.slack.com/archives/C03CVQX2A/p1661358428501249), rather than relying on the vscode provided workspace trust we use our own internal one which is determined using whether workspace trust is enabled and the status of the current workspace.
> fix: check if workspace trust is enabled when determining trust status

- package.json
- src/commands/common.ts
- src/commands/index.ts
- src/constants.ts
- src/extension.ts
This PR builds upon the [recent titanium-editor-commons changes](https://github.com/tidev/titanium-editor-commons/releases/tag/v2.1.0) that added an `issues` array to the `validateEnvironment` function, which for now only checks that the selected SDK is installed.
On startup we now check if there are any issues with the environment and prompt the user to fix them before continuing on, given that these are intended to be problems with the environment that mean the extension cannot function til they are resolved we block loading until they are fixed.
Some potential future work here might be validating the `ti info` output and raising issues shown there.
The warning message looks like this
And the sidebar view looks like this
> feat: add environment issues handling

- .github/workflows/integration-tests.yml
- .vscode/launch.json
- package-lock.json
- package.json
- patches/vscode-extension-tester-locators+3.4.0.patch
- src/test/integration/runTests.ts
- src/test/integration/util/project.ts
Updates vscode-extension-tester to the latest version and applies a patch to the locators for a change in VS Code 1.76.0 that breaks the platform select quickpicks
> chore: update vscode-extension-tester

- package.json
- src/explorer/nodes/moduleBuildNode.ts
- src/explorer/nodes/modulePackageNode.ts
- src/explorer/nodes/platformNode.ts
When a module is project is "selected" (i.e the first Titanium project loaded in the workspace) the
build explorer will now show simplified options of only Build and Package for the build choices
Closes #993
> feat(explorer/build): only show relevant build options when module project is selected

- src/explorer/nodes/build/platformNode.ts
- src/tasks/buildTaskProvider.ts
- src/tasks/helpers/base.ts
- src/types/cli.ts
Marking draft as this is a WIP, would like to test debugging and other items first but am struggling to be able to build to macOS on my machine 🤷🏻 
Closes #1129
> feat: support building for macos

- src/extension.ts
- src/providers/index.ts
In the initial load of projects we do not have environment information data and therefore no SDK data to generate completions from. So once we have loaded that environment data generate completions data for all of the app projects we have loaded.
Closes #1165
> fix(providers): always generate completion data after info load

- src/quickpicks/build/ios.ts
- src/tasks/helpers/base.ts
- src/test/unit/suite/utils.test.ts
- src/utils.ts
added: open in xcode, selecting provisioning profile for MacCatalyst (needs PR for titanium-sdk -> follows)
> fix: building for MacAppStore

- .github/workflows/release.yml
I think I missed this when configuring initially, will make sure the latest release is uploaded to Open VSX
> ci: pass OVSX_PAT to release command

- package.json
- src/commands/common.ts
- src/providers/code-action/viewCodeActionProvider.ts
- src/providers/definition/common.ts
- src/providers/index.ts
- src/test/unit/suite/providers/code-action/view.test.ts
- tsconfig.json
Implements a new [refactoring action](https://code.visualstudio.com/docs/editor/refactoring#_refactoring-actions) for views that allows extracting the properties from a tag and inserting them into the related TSS document. This can be triggered via the usual refactor shortcut, menu item, or lightbulb. 
Some known todos (hence draft status) are:
* ~Support nested properties (font only?)~
* ~Multiline properties~
* Better handling of class merging (currently only merging classes when performing whole line extraction)
* Tests!
A demonstration is below, it first demonstrates extracting a select group of properties and then extract properties from the current line the cursor is on.
https://github.com/tidev/vscode-titanium/assets/8705251/8f9bb5a3-6ab9-435c-88d2-af9b6235939a
> Add support for extracting styles to tss

- README.md
- package.json
- package.nls.json
- release.config.js
- scripts/render.js
Updates the semantic-release config to add the built docs to the version bump commit.
Also updates the docs build script to grab the value from the package.nls.json file
> Include docs in version bump commit, lookup English l10n value when building docs
